---
title: "module_13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(dplyr)
library(ggplot2)
library(leaflet)
library(scales)
library(ggmap)
library(readr)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)
library(raster)

```

```{r}
## Read in shapefile using sf
yukon_outline <- read_sf("~/Box/W20/Squanga_Paper/GIS_Data/Yukon_outline.shp")

plot(yukon_outline)  

canada <- read_sf("~/Box/F20/GIS/lpr_000b16a_e/lpr_000b16a_e.shp")
plot(canada)  


```

```{r}
worldmap <- ne_countries(scale = 'medium', type = 'map_units',
                         returnclass = 'sf')
# have a look at these two columns only
head(worldmap[c('name', 'continent')])
ggplot() + geom_sf(data = worldmap) + theme_bw()



```


```{r}
class(yukon_outline)
head(yukon_outline)
st_crs(yukon_outline)
```

```{r}
rivers <- read_sf("~/Box/W20/Squanga_Paper/GIS_Data/Squanga_Rivers.shp")
lakes <- read_sf("~/Box/W20/Squanga_Paper/GIS_Data/Squanga_Lakes.shp")

crs_yukon <- st_crs(rivers)

rivers_cropped <- st_crop(rivers, xmin = -134.1, xmax = -133.3,
                                    ymin = 60.25, ymax = 60.65)

lakes_cropped <- st_crop(lakes, xmin = -134.1, xmax = -133.3,
                                    ymin = 60.25, ymax = 60.65)

plot(rivers)
plot(lakes)
```

## Maps

Finalizing maps with ggplot

```{r}
ggplot(yukon_outline) +
  geom_sf(data = yukon_outline, col = 1) +
  theme_bw() 

# put aes in the geom_sf
```


```{r}
ggplot() +
  geom_sf(data = lakes,col  = "light blue", fill = "light blue") +
  geom_sf(data = rivers,col  = "light blue", fill = "light blue") +
  theme_bw() +
  
  # scale_x_continuous(breaks = seq(-134.1, -133.3, by = 0.1)) 
```

## Raster basemaps

```{r}
pop_3857 <- pop_3338 %>%
  st_transform(crs = 3857)
```


```{r}
# Define a function to fix the bbox to be in EPSG:3857
# See https://github.com/dkahle/ggmap/issues/160#issuecomment-397055208
ggmap_bbox_to_3857 <- function(map) {
  if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
  # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
  # and set the names to what sf::st_bbox expects:
  map_bbox <- setNames(unlist(attr(map, "bb")), 
                       c("ymin", "xmin", "ymax", "xmax"))
  
  # Coonvert the bbox to an sf polygon, transform it to 3857, 
  # and convert back to a bbox (convoluted, but it works)
  bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))
  
  # Overwrite the bbox of the ggmap object with the transformed coordinates 
  attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
  attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
  attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
  attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
  map
}
```

```{r}
bbox <- c(-170, 52, -130, 64)   # This is roughly southern Alaska
ak_map <- get_stamenmap(bbox, zoom = 4)
ak_map_3857 <- ggmap_bbox_to_3857(ak_map)

ggmap(ak_map_3857) + 
  geom_sf(data = pop_3857, aes(color = population), inherit.aes = F) +
  scale_color_continuous(low = "khaki", high =  "firebrick", labels = comma)
  # scale_x_continuous(breaks = seq(-170, 130, by = 10))

```

## Leaflet

```{r}
epsg3338 <- leaflet::leafletCRS(
  crsClass = "L.Proj.CRS",
  code = "EPSG:3338",
  proj4def =  "+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
  resolutions = 2^(16:7))

st_crs(pop_region_3338)

pop_region_4326 <- pop_region_3338 %>% st_transform(crs = 4326)

pal <- colorNumeric(palette = "Reds", domain = pop_region_4326$total_pop)

m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
        addPolygons(data = pop_region_4326, 
                    fillColor = ~pal(total_pop),
                    weight = 1,
                    color = "black",
                    fillOpacity = 1,
                    label = ~region) %>% 
        addLegend(position = "bottomleft",
                  pal = pal,
                  values = range(pop_region_4326$total_pop),
                  title = "Total Population")

m



```
